# Generated by Django 2.2.19 on 2023-03-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230318_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='adress',
            new_name='slug',
        ),
    ]
